/**
 * Serialize the neutral Design model to the xTool `.xcs` file format.
 *
 * The `.xcs` format is community-reverse-engineered (see docs/xcs-format.md).
 * Key facts this implementation relies on (high confidence, confirmed against
 * real Studio-produced sample files and two independent generators):
 *
 *  - `.xcs` is plain, uncompressed JSON.
 *  - Shapes ("displays") live in `canvas[0].displays`; coordinates are mm,
 *    origin = top-left of each shape's bounding box.
 *  - Laser parameters do NOT live on the shape. They live in a parallel
 *    `device.data` structure: a JS Map serialized as
 *    `{ "dataType": "Map", "value": [[canvasId, {...}]] }`, whose per-canvas
 *    object contains a nested `displays` Map keyed by shape id.
 *  - Passes are written as `repeat` (not "passes").
 *  - A CIRCLE must set `scale = width / 5900` or Studio renders it invisible.
 *
 * This targets the single-file `.xcs` JSON (the well-trodden D1/F1-class path),
 * not the newer zip-based `.xs` workspace bundle.
 */
import { getMachine } from "../knowledge.js";
import type { LaserCategory, Machine } from "../types.js";
import { shapeToPathD, type Design, type OpParams, type Shape } from "./design.js";

export const XCS_FORMAT_NOTE =
  "Generated by xtool-mcp. .xcs is a reverse-engineered format; open in xTool Studio/XCS and verify before running. Test on scrap.";

/** MOPA pulse widths (ns) the firmware accepts; other values are rejected. */
export const LEGAL_PULSE_WIDTHS_NS = [
  2, 4, 6, 9, 13, 20, 30, 45, 60, 80, 100, 150, 200, 250, 350, 500
] as const;

export interface BuildXcsOptions {
  /** Machine object or id/name; used to fill extId/extName and light source. */
  machine?: Machine | string;
  /** Explicit xTool model code (e.g. "D1"). Overrides machine-derived value. */
  extId?: string;
  extName?: string;
  /** "blue" = diode, "red" = fiber/MOPA. Defaults from the machine category. */
  lightSource?: "blue" | "red";
  /** Material thickness in mm (used by Studio for autofocus). */
  materialThicknessMm?: number;
  /** Override the app version string written to the file. */
  version?: string;
}

type ProcessingType =
  | "VECTOR_CUTTING"
  | "VECTOR_ENGRAVING"
  | "COLOR_FILL_ENGRAVE";

function uuid(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  // Fallback (non-crypto) for older runtimes.
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (ch) => {
    const r = (Math.random() * 16) | 0;
    return (ch === "x" ? r : (r & 0x3) | 0x8).toString(16);
  });
}

function lightSourceFor(category: LaserCategory | undefined): "blue" | "red" {
  if (category === "fiber" || category === "infrared") return "red";
  return "blue";
}

function processingTypeFor(op: OpParams): ProcessingType {
  switch (op.type) {
    case "cut":
      return "VECTOR_CUTTING";
    case "score":
      return "VECTOR_ENGRAVING";
    case "engrave":
      return "COLOR_FILL_ENGRAVE";
  }
}

interface Bounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

function shapeBounds(shape: Shape): Bounds {
  switch (shape.kind) {
    case "rect":
      return { x: shape.x, y: shape.y, width: shape.width, height: shape.height };
    case "ellipse":
      return {
        x: shape.cx - shape.rx,
        y: shape.cy - shape.ry,
        width: shape.rx * 2,
        height: shape.ry * 2
      };
    case "line":
      return {
        x: Math.min(shape.x1, shape.x2),
        y: Math.min(shape.y1, shape.y2),
        width: Math.abs(shape.x2 - shape.x1),
        height: Math.abs(shape.y2 - shape.y1)
      };
    case "polyline":
    case "polygon": {
      const xs = shape.points.map((p) => p[0]);
      const ys = shape.points.map((p) => p[1]);
      const minX = Math.min(...xs);
      const minY = Math.min(...ys);
      return { x: minX, y: minY, width: Math.max(...xs) - minX, height: Math.max(...ys) - minY };
    }
    case "text":
      return {
        x: shape.x,
        y: shape.y - shape.fontSize,
        width: Math.max(1, shape.text.length * shape.fontSize * 0.6),
        height: shape.fontSize
      };
    case "path":
      return estimatePathBounds(shape.d);
  }
}

/** Rough bbox for an absolute-coordinate SVG path (used for imported paths). */
function estimatePathBounds(d: string): Bounds {
  const nums = (d.match(/-?\d*\.?\d+(?:e-?\d+)?/gi) ?? []).map(Number);
  const xs: number[] = [];
  const ys: number[] = [];
  for (let i = 0; i + 1 < nums.length; i += 2) {
    xs.push(nums[i]!);
    ys.push(nums[i + 1]!);
  }
  if (xs.length === 0) return { x: 0, y: 0, width: 0, height: 0 };
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  return { x: minX, y: minY, width: Math.max(...xs) - minX, height: Math.max(...ys) - minY };
}

function buildDisplay(shape: Shape): Record<string, unknown> {
  const b = shapeBounds(shape);
  const isFill = shape.op.type === "engrave";
  const common: Record<string, unknown> = {
    id: shape.id,
    name: null,
    x: round(b.x),
    y: round(b.y),
    angle: 0,
    scale: { x: 1, y: 1 },
    skew: { x: 0, y: 0 },
    pivot: { x: 0, y: 0 },
    localSkew: { x: 0, y: 0 },
    offsetX: round(b.x),
    offsetY: round(b.y),
    lockRatio: false,
    zOrder: 0,
    groupTags: [],
    width: round(b.width),
    height: round(b.height),
    isFill,
    lineColor: 0,
    fillColor: "#000000"
  };

  switch (shape.kind) {
    case "rect":
      return { ...common, type: "RECT", isClosePath: true };
    case "ellipse": {
      if (Math.abs(shape.rx - shape.ry) < 1e-6) {
        const diameter = shape.rx * 2;
        // CRITICAL: CIRCLE requires scale = width / 5900 or it renders invisible.
        return {
          ...common,
          type: "CIRCLE",
          isClosePath: true,
          lockRatio: true,
          scale: { x: diameter / 5900, y: diameter / 5900 }
        };
      }
      return { ...common, type: "PATH", isClosePath: true, points: [], dPath: shapeToPathD(shape) };
    }
    case "line":
      return {
        ...common,
        type: "PATH",
        isClosePath: false,
        points: [],
        dPath: shapeToPathD(shape)
      };
    case "polyline":
    case "polygon":
      return {
        ...common,
        type: "PATH",
        isClosePath: shape.kind === "polygon",
        points: [],
        dPath: shapeToPathD(shape)
      };
    case "path":
      return { ...common, type: "PATH", isClosePath: true, points: [], dPath: shape.d };
    case "text":
      return {
        ...common,
        type: "TEXT",
        text: shape.text,
        style: {
          fontFamily: "Arial",
          fontSubfamily: "Regular",
          fontSource: "build-in",
          fontSize: shape.fontSize,
          letterSpacing: 0,
          leading: shape.fontSize * 1.2,
          align: "left"
        }
      };
  }
}

function clampNum(v: number, min: number, max: number): number {
  if (!Number.isFinite(v)) return min;
  return Math.min(max, Math.max(min, v));
}

function buildProcessingEntry(shape: Shape, lightSource: "blue" | "red"): Record<string, unknown> {
  const pt = processingTypeFor(shape.op);
  const isFill = shape.op.type === "engrave";
  // Clamp to physically valid ranges so a stray parameter can't emit an unsafe/invalid job.
  const customize: Record<string, unknown> = {
    power: clampNum(shape.op.power_pct, 0, 100),
    speed: Math.max(0.1, Number.isFinite(shape.op.speed_mm_s) ? shape.op.speed_mm_s : 100),
    repeat: clampNum(Math.round(shape.op.passes), 1, 50),
    processingLightSource: lightSource,
    pulseWidth: 200,
    mopaFrequency: 65
  };
  if (pt === "COLOR_FILL_ENGRAVE") {
    customize.density = 100;
    customize.dpi = clampNum(Math.round(shape.op.dpi ?? 300), 10, 4000);
    customize.dotDuration = 100;
    customize.bitmapEngraveMode = "normal";
    customize.bitmapScanMode = "zMode";
    customize.scanAngle = 90;
    customize.angleType = 1;
    customize.crossAngle = false;
  } else {
    customize.enableKerf = false;
    customize.kerfDistance = 0;
  }

  return {
    type: displayType(shape),
    isFill,
    processingType: pt,
    processIgnore: false,
    data: {
      [pt]: {
        materialType: "customize",
        parameter: { customize }
      }
    }
  };
}

function displayType(shape: Shape): string {
  if (shape.kind === "rect") return "RECT";
  if (shape.kind === "text") return "TEXT";
  if (shape.kind === "ellipse" && Math.abs(shape.rx - shape.ry) < 1e-6) return "CIRCLE";
  return "PATH";
}

function round(v: number): number {
  return Math.round(v * 1000) / 1000;
}

export interface BuiltXcs {
  /** The `.xcs` document as a JS object. */
  doc: Record<string, unknown>;
  /** Pretty-printed JSON string ready to write to a `.xcs` file. */
  json: string;
  extId: string;
  extName: string;
  warnings: string[];
}

export function buildXcs(design: Design, options: BuildXcsOptions = {}): BuiltXcs {
  const warnings: string[] = [];
  const machine =
    typeof options.machine === "string" ? getMachine(options.machine) : options.machine;

  const curatedExtId = machine?.xcs_ext_id;
  const extId = options.extId ?? curatedExtId ?? deriveExtId(machine);
  const extName =
    options.extName ?? machine?.xcs_ext_name ?? machine?.name?.replace(/^xTool\s+/i, "") ?? extId;
  const lightSource = options.lightSource ?? lightSourceFor(machine?.category);

  if (!options.extId && !curatedExtId) {
    warnings.push(
      machine
        ? `extId was derived as "${extId}" and is NOT a verified xTool model code — confirm it in Studio, or pass extId explicitly.`
        : "No machine specified; extId defaulted. Set the correct machine so Studio targets the right device."
    );
  }

  const canvasId = uuid();
  const now = Date.now();

  const displays = design.shapes.map(buildDisplay);
  const processingPairs = design.shapes.map((shape) => [
    shape.id,
    buildProcessingEntry(shape, lightSource)
  ]);

  const doc: Record<string, unknown> = {
    canvasId,
    version: options.version ?? "1.7.24",
    extId,
    extName,
    created: now,
    modify: now,
    ua: "xtool-mcp",
    meta: [],
    projectTraceID: uuid(),
    canvas: [
      {
        id: canvasId,
        title: design.meta?.title ? design.meta.title.slice(0, 40) : "{panel}1",
        displays
      }
    ],
    device: {
      id: extId,
      extId,
      extName,
      power: machine ? (machine.laser_power_w[machine.laser_power_w.length - 1] ?? 0) : 0,
      materialList: [],
      data: {
        dataType: "Map",
        value: [
          [
            canvasId,
            {
              mode: "LASER_PLANE",
              data: {
                LASER_PLANE: {
                  material: 0,
                  thickness: options.materialThicknessMm ?? null,
                  lightSourceMode: lightSource
                }
              },
              displays: {
                dataType: "Map",
                value: processingPairs
              }
            }
          ]
        ]
      }
    }
  };

  return { doc, json: JSON.stringify(doc, null, 2), extId, extName, warnings };
}

function deriveExtId(machine: Machine | undefined): string {
  if (!machine) return "D1";
  // Best-effort: strip "xTool " and spaces. Known codes should be curated in data.
  return machine.name.replace(/^xTool\s+/i, "").replace(/\s+/g, "").toUpperCase();
}
